"""
Core data models and enums for the Self-Healing Deployment System.

This module defines the fundamental data structures used throughout the self-healing
system for error detection, analysis, fix generation, application, verification, and
learning. All models use Python 3.11+ dataclasses with comprehensive type hints and
docstrings.

Requirements: 1.3, 1.4, 1.5, 3.1, 4.1, 6.1, 6.2
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class ErrorSeverity(Enum):
    """
    Enumeration of error severity levels.

    Severity levels are used to prioritize error analysis and fix application:
    - CRITICAL: Errors in core components (Intake_Node, Root_Orchestrator, Synthesizer)
    - HIGH: Errors in domain orchestrators or test failures with broad impact
    - MEDIUM: Errors in leaf nodes or single-component failures
    - LOW: Non-blocking errors or warnings
    - INFO: Informational messages (deprecation warnings, etc.)

    Requirements: 11.1
    """

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class FixStatus(Enum):
    """
    Enumeration of fix proposal and application statuses.

    Status progression:
    - PENDING: Fix generated, awaiting application
    - APPLIED: Fix applied to source code
    - VERIFIED: Fix verified through testing
    - FAILED: Fix application or verification failed
    - REVERTED: Fix was applied but then rolled back

    Requirements: 1.4
    """

    PENDING = "PENDING"
    APPLIED = "APPLIED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    REVERTED = "REVERTED"


@dataclass
class ErrorReport:
    """
    Structured record of a detected error.

    Captures all relevant information about an error including type, message,
    severity, stack trace, and execution context. Used as the primary input
    to error analysis and fix generation.

    Attributes:
        error_id: Unique identifier (UUID) for this error
        error_type: Exception class name or error type string
        message: Human-readable error message
        severity: ErrorSeverity classification (CRITICAL, HIGH, MEDIUM, LOW, INFO)
        timestamp: When the error was detected
        component: Name of Kabbalah component where error occurred
        context: Execution context dict (trace_id, request_id, etc.)
        stack_trace: Full stack trace from exception
        file_path: Source file where error occurred
        line_number: Line number in source file
        occurrence_count: Number of times identical error occurred (for deduplication)
        status: Current status of error (DETECTED, ANALYZED, FIXED, VERIFIED, FAILED)

    Requirements: 1.3, 1.4, 1.5
    """

    error_id: str
    """Unique identifier (UUID) for this error"""

    error_type: str
    """Exception class name or error type string"""

    message: str
    """Human-readable error message"""

    severity: ErrorSeverity
    """Error severity classification"""

    timestamp: datetime
    """When the error was detected"""

    component: str
    """Name of Kabbalah component where error occurred"""

    context: Dict[str, Any]
    """Execution context (trace_id, request_id, etc.)"""

    stack_trace: str
    """Full stack trace from exception"""

    file_path: str
    """Source file where error occurred"""

    line_number: int
    """Line number in source file"""

    occurrence_count: int = 1
    """Number of times identical error occurred (for deduplication)"""

    status: str = "DETECTED"
    """Current status of error (DETECTED, ANALYZED, FIXED, VERIFIED, FAILED)"""


@dataclass
class CodeChange:
    """
    Individual file change within a fix proposal.

    Represents a single file modification including the original content,
    new content, line range, and diff for audit and rollback purposes.

    Attributes:
        file_path: Path to file being modified
        original_content: Original file content before change
        new_content: New file content after change
        line_start: Starting line number of change
        line_end: Ending line number of change
        diff: Unified diff format of the change

    Requirements: 3.1
    """

    file_path: str
    """Path to file being modified"""

    original_content: str
    """Original file content before change"""

    new_content: str
    """New file content after change"""

    line_start: int
    """Starting line number of change"""

    line_end: int
    """Ending line number of change"""

    diff: str
    """Unified diff format of the change"""


@dataclass
class FixProposal:
    """
    Proposed fix with code changes and confidence scoring.

    Generated by the Fix_Generation_Module from error analysis. Contains all
    information needed to apply, verify, and learn from a fix. Confidence score
    determines whether manual review is required before application.

    Attributes:
        fix_id: Unique identifier (UUID) for this fix proposal
        error_id: ID of error this fix addresses
        description: Human-readable description of the fix
        code_changes: List of CodeChange objects for this fix
        confidence_score: LLM confidence in fix (0.0-1.0)
        reasoning: Detailed reasoning explaining why fix addresses root cause
        affected_files: List of file paths affected by this fix
        requires_manual_review: True if confidence < 0.5 or other safety concerns
        status: Current status (PENDING, APPLIED, VERIFIED, FAILED, REVERTED)
        timestamp: When fix was generated

    Requirements: 3.1, 3.4, 3.8
    """

    fix_id: str
    """Unique identifier (UUID) for this fix proposal"""

    error_id: str
    """ID of error this fix addresses"""

    description: str
    """Human-readable description of the fix"""

    code_changes: List[CodeChange]
    """List of CodeChange objects for this fix"""

    confidence_score: float
    """LLM confidence in fix (0.0-1.0)"""

    reasoning: str
    """Detailed reasoning explaining why fix addresses root cause"""

    affected_files: List[str]
    """List of file paths affected by this fix"""

    requires_manual_review: bool
    """True if confidence < 0.5 or other safety concerns"""

    status: FixStatus = FixStatus.PENDING
    """Current status (PENDING, APPLIED, VERIFIED, FAILED, REVERTED)"""

    timestamp: datetime = field(default_factory=datetime.now)
    """When fix was generated"""


@dataclass
class Checkpoint:
    """
    Backup state for rollback capability.

    Created before applying a fix, contains all affected file contents and
    system state. Retained for 24 hours to allow rollback if fix fails
    verification or causes regressions.

    Attributes:
        checkpoint_id: Unique identifier (UUID) for this checkpoint
        timestamp: When checkpoint was created
        affected_files: List of file paths included in checkpoint
        file_contents: Dict mapping file_path -> original content
        system_state: Dict of system state at checkpoint time
        retention_until: Datetime when checkpoint expires (24 hours from creation)

    Requirements: 4.1, 4.7, 14.1
    """

    checkpoint_id: str
    """Unique identifier (UUID) for this checkpoint"""

    timestamp: datetime
    """When checkpoint was created"""

    affected_files: List[str]
    """List of file paths included in checkpoint"""

    file_contents: Dict[str, str]
    """Dict mapping file_path -> original content"""

    system_state: Dict[str, Any]
    """Dict of system state at checkpoint time"""

    retention_until: datetime
    """Datetime when checkpoint expires (24 hours from creation)"""


@dataclass
class LearningEntry:
    """
    Stored pattern for fix reuse and learning.

    Created when a fix is successfully verified. Contains the error pattern,
    fix details, and usage/success tracking. Used to accelerate fix application
    for recurring errors and to provide context for new error analysis.

    Attributes:
        entry_id: Unique identifier (UUID) for this learning entry
        error_pattern: Normalized error pattern (type + message hash)
        error_type: Exception class name or error type
        error_message_pattern: Normalized error message pattern
        fix_description: Description of the fix
        code_changes: List of CodeChange objects from the fix
        reasoning: Reasoning explaining why fix addresses root cause
        confidence_score: Confidence in this fix (0.0-1.0, updated based on usage)
        usage_count: Number of times this fix has been applied
        success_count: Number of times this fix succeeded
        failure_count: Number of times this fix failed
        success_rate: Calculated success rate (success_count / usage_count)
        created_at: When this entry was created
        last_used_at: When this fix was last applied
        archived: True if entry is archived (>30 days old)

    Requirements: 6.1, 6.2, 6.6, 6.7
    """

    entry_id: str
    """Unique identifier (UUID) for this learning entry"""

    error_pattern: str
    """Normalized error pattern (type + message hash)"""

    error_type: str
    """Exception class name or error type"""

    error_message_pattern: str
    """Normalized error message pattern"""

    fix_description: str
    """Description of the fix"""

    code_changes: List[CodeChange]
    """List of CodeChange objects from the fix"""

    reasoning: str
    """Reasoning explaining why fix addresses root cause"""

    confidence_score: float
    """Confidence in this fix (0.0-1.0, updated based on usage)"""

    usage_count: int = 0
    """Number of times this fix has been applied"""

    success_count: int = 0
    """Number of times this fix succeeded"""

    failure_count: int = 0
    """Number of times this fix failed"""

    success_rate: float = 0.0
    """Calculated success rate (success_count / usage_count)"""

    created_at: datetime = field(default_factory=datetime.now)
    """When this entry was created"""

    last_used_at: Optional[datetime] = None
    """When this fix was last applied"""

    archived: bool = False
    """True if entry is archived (>30 days old)"""
